# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MDFlickerImages' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MMNetworkManager'

  target 'MDFlickerImagesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MDFlickerImagesUITests' do
    # Pods for testing
  end

end
